### PR TITLE
cslogin: ssabar - add benchmarks

### PR DESCRIPTION
**Pull request by sethsabar**

### CODE REVIEW

**Comment by jchen** [comment]
@sethsabar Can you make sure that all your tests are valid lisp syntax? (Looks like you have an infix equality operator somewhere). Thanks!

**Comment by sethsabar** [comment]
> @sethsabar Can you make sure that all your tests are valid lisp syntax? (Looks like you have an infix equality operator somewhere). Thanks!

Just fixed that error!

**Comment by jchen** [comment]
@sethsabar Sorry to add on - if you have `(read-num)` in your test programs, you should also include `.in` files for those tests!

**Comment by sethsabar** [comment]
> @sethsabar Sorry to add on - if you have `(read-num)` in your test programs, you should also include `.in` files for those tests!

Fixed!

**Comment by jchen** [comment]
Looks good - thanks!

**Pull request merged**
